name: Deploy to Firebase Hosting

on:
  push:
    branches: [ master ]

concurrency:
  group: firebase-hosting
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install deps & build
        run: |
          npm ci
          npm run build

      - name: Verify Hosting folder exists
        run: |
          test -d out || { echo "::error::Expected 'out' folder not found. Check package.json build or firebase.json"; exit 1; }

      - name: Deploy Hosting
        run: npx firebase-tools deploy --only hosting --project "${{ secrets.FIREBASE_PROJECT_ID }}"
